Updated forms to have better input validation
j-selby/CASS-Degrees-Code pull request #148
Opened 2019-05-14 15:00 UTC by KavsHub

This addresses the wishes of #131 #130 and a bug fix in subplan creation that I found along the way. 
I've added a lot of strict validation that follows the standards from Programs and Courses.
Firstly all codes are now saved as uppercase, even if the user enters in lowercase or mixed.
All units must be divisible by 6.

**SUBPLANS**
Subplan now checks for the plan type in the course code
<img width="798" alt="Capture" src="https://user-images.githubusercontent.com/44992275/57707626-4627a800-76ab-11e9-95de-675da64d0821.PNG">
Subplan codes should have a '-' to split its plan type
<img width="805" alt="Capture2" src="https://user-images.githubusercontent.com/44992275/57707628-4627a800-76ab-11e9-9d4b-d9b1c73c48f9.PNG">
Subplans names shouldn't have the plan type as the code is made for that #131 
<img width="783" alt="Capture3" src="https://user-images.githubusercontent.com/44992275/57707630-46c03e80-76ab-11e9-991c-722a48fd962d.PNG">
I actually found this bug and fixed it, if nothing is selected we get a keyerror. I fixed this by catching the error and notifying the user to fill all fields
<img width="795" alt="Capture4" src="https://user-images.githubusercontent.com/44992275/57707631-4758d500-76ab-11e9-8477-13d8f3f91386.PNG">

**COURSES**
We now have very strict course codes which follow the current P&C syntax
If not 4 letters at the start
<img width="731" alt="Capture5" src="https://user-images.githubusercontent.com/44992275/57707632-4758d500-76ab-11e9-9e0b-4390511456f0.PNG">
if not 4 numbers after
<img width="768" alt="Capture6" src="https://user-images.githubusercontent.com/44992275/57707634-47f16b80-76ab-11e9-97b2-83ebb0e55c84.PNG">
if code is too long or short
<img width="783" alt="Capture7" src="https://user-images.githubusercontent.com/44992275/57707635-47f16b80-76ab-11e9-9960-fa6f5dd78204.PNG">
I added this because codes are not all length 8, some codes have A, B C on them so I added an optional letter for it
<img width="759" alt="Capture9" src="https://user-images.githubusercontent.com/44992275/57707637-488a0200-76ab-11e9-8395-5ffd23c912d5.PNG">

Please tell me what you think. I think this is good for ensuring accurate data and I've followed all the Programs and courses standards.

Also, let me know if theres any more strict checks you want me to do.

2019-05-14 15:00 UTC, pep8speaks commented
Hello @KavsHub! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cassdegrees/ui/forms.py`](https://github.com/cass-degrees/CASS-Degrees-Code/blob/8a786e8cca781ecfbdbcbc8fda958d62f270d7ec/cassdegrees/ui/forms.py):

> [Line 216:20](https://github.com/cass-degrees/CASS-Degrees-Code/blob/8a786e8cca781ecfbdbcbc8fda958d62f270d7ec/cassdegrees/ui/forms.py#L216): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2019-05-15 03:14 UTC, j-selby requested changes
Looks good.

2019-05-15 03:14 UTC, j-selby commented on cassdegrees/ui/forms.py
> +        print(len(data))
Unneeded print statement

2019-05-15 03:54 UTC, KavsHub commented on cassdegrees/ui/forms.py
> +        print(len(data))
Thanks haha.

2019-05-15 05:54 UTC, JackSekoranja approved these changes
Looks good. I should mention that CASS currently offers a Major with the word 'Major' in the title ([Animation and Video Major](https://programsandcourses.anu.edu.au/2019/major/ANVI-MAJ)), so we wouldn't be able to add that to the system currently. However, I understand this was a specific UAT request, so it may be a good idea to bring this up next client meeting (and admittedly this seems to be the only Subplan with the Subplan type in the name).

2019-05-15 05:56 UTC, KavsHub commented
> Looks good. I should mention that CASS currently offers a Major with the word 'Major' in the title ([Animation and Video Major](https://programsandcourses.anu.edu.au/2019/major/ANVI-MAJ)), so we wouldn't be able to add that to the system currently. However, I understand this was a specific UAT request, so it may be a good idea to bring this up next client meeting (and admittedly this seems to be the only Subplan with the Subplan type in the name).

I feel like that was a CASS mistake haha

2019-05-15 11:22 UTC, KavsHub commented
This PR addresses 6 issues now since I've combined a lot of small UAT issues and other issues in the backlog which were mostly 1 line changes or small fixes. 
Going to merge this once I've tested it thoroughly

2019-05-15 11:55 UTC, merged