Course Requisites and Incompatibilities
j-selby/CASS-Degrees-Code pull request #156
Opened 2019-05-21 10:30 UTC by spencerj411

Aims to complete #81 and #78.
This pr contains the following additions/modification:

- added `rules` field to CourseModel
- added either/or rule to course
- added requisite/incompatibility section in the form
- added program field to requisite
- added incompatibility option
- added year-level field to subject-area units to satisfy all criteria (eg. 12 units of COMP 4000-level courses)

**Whilst creating a course**
![image](https://user-images.githubusercontent.com/24206502/58088889-f6933000-7c06-11e9-9a5c-81a3605614d1.png)

**Once it has been saved**
![image](https://user-images.githubusercontent.com/24206502/58088989-2b9f8280-7c07-11e9-9e63-ae90c6f6847f.png)

2019-05-22 01:49 UTC, j-selby approved these changes
Nice work!

2019-05-22 01:49 UTC, j-selby commented on cassdegrees/templates/createcourse.html
> +{#            <!-- TODO: Unhandled so far -->#}
Wait, can this be removed now?

2019-05-22 01:49 UTC, j-selby commented on cassdegrees/templates/widgets/rulescripts.html
> +{% endverbatim %}
Newline

2019-05-22 04:06 UTC, JackSekoranja requested changes
I did find a few things that we might want to change:
- 'Course' and 'Incompatibility' should work the same. Maybe remove the unit count from 'Course' and re-name it 'Course Requisite'
- It says "Students must be studying a program which includes:", but you can only select one option
- There is a unit count on custom-text items. We might not want this since it may be things like "Students need to get a permission code for this course"
- Units is also mentioned in other places (Subject-area, Level-specific), but it may not make sense in this context

![Screen Shot 2019-05-22 at 2 00 11 pm](https://user-images.githubusercontent.com/36946090/58146574-0d369700-7c9a-11e9-92df-7dacd7eb3a85.jpg)

Otherwise it looks very good, well done :)

2019-05-27 02:10 UTC, Daniel-Jang commented
@JackSekoranja I had a look at your comment and the first 3 dot points I agree with. However, with your 4th point, there are cases where a course requisite would be like "... and 6 units of 1000 level MATH":
https://programsandcourses.anu.edu.au/2019/course/COMP2100

I will fix everything else, however, since you raised valid points about them.

2019-05-27 05:16 UTC, JackSekoranja approved these changes
Looks good

2019-05-27 06:05 UTC, merged