Added Cancel Buttons to Create/Edit pages
j-selby/CASS-Degrees-Code pull request #159
Opened 2019-05-22 09:39 UTC by KavsHub

As requested, there's now a cancel button on the create/edit pages.

2019-05-23 09:59 UTC, JackSekoranja requested changes
Works well, but could you do the same for program/subplan/course deletion? After that I believe that will be everything we need

2019-05-23 11:37 UTC, KavsHub commented
> Works well, but could you do the same for program/subplan/course deletion? After that I believe that will be everything we need

I thought there was already yes - no buttons but apparently not anymore. I've updated them now

2019-05-23 13:35 UTC, JackSekoranja approved these changes
Looks good, happy for you to merge

2019-05-24 00:59 UTC, j-selby commented on cassdegrees/static/js/main.js
>  }
Newline

2019-05-24 04:12 UTC, merged