Code Fixes and Improvements
j-selby/CASS-Degrees-Code pull request #160
Opened 2019-05-23 09:52 UTC by JackSekoranja

This PR achieves the following:
- Adds a 'publish' option to program plans, as requested by the original Issue (#19)
- Prevented submission if there are error messages in the Program form
- Unpublished Subplans can no longer be selected
- Subplans now restricted to the entered program year
   - Adding a 'subplan' vue component will automatically set up the 'year' field to update all components when the year changes
   - If the year changes when subplans are selected, the entered will need to be re-selected

2019-05-23 09:52 UTC, pep8speaks commented
Hello @JackSekoranja! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cassdegrees/api/serializers.py`](https://github.com/cass-degrees/CASS-Degrees-Code/blob/666c81d4ac33280258a8c76f0333c5bd91046252/cassdegrees/api/serializers.py):

> [Line 27:121](https://github.com/cass-degrees/CASS-Degrees-Code/blob/666c81d4ac33280258a8c76f0333c5bd91046252/cassdegrees/api/serializers.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)

* In the file [`cassdegrees/ui/forms.py`](https://github.com/cass-degrees/CASS-Degrees-Code/blob/666c81d4ac33280258a8c76f0333c5bd91046252/cassdegrees/ui/forms.py):

> [Line 37:121](https://github.com/cass-degrees/CASS-Degrees-Code/blob/666c81d4ac33280258a8c76f0333c5bd91046252/cassdegrees/ui/forms.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2019-05-26 03:53 UTC, j-selby requested changes
Looks good!

2019-05-26 03:53 UTC, j-selby commented on cassdegrees/static/js/rules.js
> +function redrawVueComponents(){
space after ()

2019-05-26 03:53 UTC, j-selby commented on cassdegrees/static/js/rules.js
> +}
Newline

2019-05-26 03:53 UTC, j-selby commented on cassdegrees/templates/createprogram.html
> +            if(document.querySelector('.msg-error') !== null)
For consistency, enclose the return call in {}

2019-05-26 03:53 UTC, j-selby commented on cassdegrees/templates/widgets/rules.html
> +        <div class="msg-error" v-if="wrong_year_selected">Selected subplans must have same year as program</div>
Change to `Selected subplans must have same year as program!`

2019-05-27 06:15 UTC, Daniel-Jang approved these changes
I haven't extensively tested it but I had a quick look and play around and it seems good to me.

2019-05-27 10:04 UTC, j-selby approved these changes

2019-05-28 02:06 UTC, merged