Add "Save" and "Save and Exit" Buttons for Editing
j-selby/CASS-Degrees-Code pull request #178
Opened 2019-08-06 11:25 UTC by Daniel-Jang

Original UAT Issue: https://github.com/cass-degrees/CASS-Degrees-Code/issues/116

I have added the 'Save' button that saves the details inserted by the user, without redirecting them back to the list page.

![image](https://user-images.githubusercontent.com/37033052/62536150-97050200-b890-11e9-8ef9-0189836ded0e.png)

2019-08-06 13:04 UTC, j-selby requested changes
Looking good!

2019-08-06 13:04 UTC, j-selby commented on cassdegrees/templates/createcourse.html
> +                console.log(document);
Unneeded debugging (document object is going to be huge!)

2019-08-06 23:41 UTC, JackSekoranja approved these changes
Looks good, although I agree with James' suggested changes. I did notice that there was no 'Cancel' button when editing courses, despite there being one for Programs and Subplans. I know that isn't part of this pull request, but it's similar enough to add in this pull request since we'll need to fix it anyway.

2019-08-07 05:58 UTC, Daniel-Jang commented
I've done what James and Jack recommended, and now is ready to merge.

2019-08-07 06:06 UTC, j-selby approved these changes
Looks good!

2019-08-07 06:12 UTC, merged