Feature plan save and load
j-selby/CASS-Degrees-Code pull request #232
Opened 2019-08-21 12:59 UTC by JackSekoranja

This PR implements Issues #202, #183, #187, and #184. The primary new feature is plan saving and loading using the main menu system. This change also modifies the `student_edit.html` file by using a form and submit button rather than a link. 

The saving and loading uses `zlib` compression library, as it was experimentally found to give the best compression results for longer json strings. `bz2` and `lzma` were also tested.

**Adding New Plan Elements**
To add new details to the plan, one only needs to add an input element as with the following attributes inside the `form` element:
- `name="[Field Name]"`: The name that should be used to refer to the object
- `value="{{ plan.[Field Name] }}"`: Using that object to load existing plans

After doing this, the plan should automatically take the value inputted by the user when saving, and restore it when loading

![Screen Shot 2019-08-21 at 10 47 08 pm](https://user-images.githubusercontent.com/36946090/63433041-bb9ed380-c465-11e9-9939-440dd48ab27f.jpg)

2019-08-21 12:59 UTC, pep8speaks commented
Hello @JackSekoranja! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cassdegrees/ui/views/student.py`](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py):

> [Line 68:37](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L68): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 81:40](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L81): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 129:17](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L129): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 138:17](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L138): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 140:40](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L140): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 150:13](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L150): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 154:39](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L154): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator
> [Line 158:54](https://github.com/cass-degrees/CASS-Degrees-Code/blob/27c40a373ae552b71184c1eb8f79b35809e92fbe/cassdegrees/ui/views/student.py#L158): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

2019-08-21 14:40 UTC, aidengeorge97 requested changes
Saving a plan with no name entered returns a "sucessfully saved" message, but the plan is not actually saved. It should return an error message if you try to save without naming the plan.

2019-08-22 00:11 UTC, Daniel-Jang commented
The last modified timestamp does not show the exact time. It would be nice to see the hour and minute it was saved, as a user can work on the same plan multiple times a day. (Also it is part of the acceptance criteria for #187 ).

Also, there should be a confirmation prompt when you click on the 'Remove' button, since it is very easy to accidently click on it.

Otherwise, very good!

2019-08-22 06:29 UTC, Daniel-Jang approved these changes

2019-08-22 06:48 UTC, aidengeorge97 approved these changes
With the new changes, this is ready for merge.

2019-08-22 06:50 UTC, merged