Add verification for plan and subplan vue rules
j-selby/CASS-Degrees-Code pull request #382
Opened 2019-09-23 03:08 UTC by JackSekoranja

Closes #380

This PR will add unit verification in program plans and subplans. Furthermore, OR rules will now throw an error if there is an inconsistent number of units in each group. This functionality also supports `At Least`, `Exactly` and `No More Than` rules by bounding the unit count as the plan is evaluated.

**Error Message for Subplan Rules:**
<img width="1115" alt="Subplan MSG" src="https://user-images.githubusercontent.com/36946090/65399889-8ab61380-de02-11e9-92d1-93c690a375a1.png">

**OR Rule Error Message:**
<img width="781" alt="OR MSG" src="https://user-images.githubusercontent.com/36946090/65399890-8ab61380-de02-11e9-839b-ac7c0f69189b.png">

2019-09-23 12:34 UTC, Daniel-Jang approved these changes
Had a look, didn't face any issues. Works well.

2019-09-23 13:05 UTC, j-selby requested changes
Looks good overall, needs a few tweaks.

2019-09-23 13:05 UTC, j-selby commented on cassdegrees/templates/staff/creation/createprogram.html
> +                    !confirm("You have created a plan that contains a different number of units than you have " +
Not sure how exact this phrasing is - "different number of units than you have specified" could read better - perhaps "a different number from the number of units you specified for the entire plan"?

2019-09-23 13:05 UTC, j-selby commented on cassdegrees/templates/staff/creation/createsubplan.html
> +                    if (planType === "MAJ" && !isValidUnitCount(48) &&
Is it possible to get this from count units or similar? I'm not 100% sure about putting constants here - could this be extracted elsewhere?

2019-09-23 13:05 UTC, j-selby commented on cassdegrees/templates/widgets/staff/rules.html
> +            The number of units in each group is inconsistent. Please ensure an equal number of units.
Maybe 'Please ensure that each group has an equivalent number of units?'

2019-09-24 04:58 UTC, aidengeorge97 approved these changes
Given that the changes James has suggested have been implemented, I'm happy to accept this PR now.

2019-09-24 04:59 UTC, merged