Updated messages to make publish clearer to the user
j-selby/CASS-Degrees-Code pull request #388
Opened 2019-09-23 13:19 UTC by KavsHub

Addresses issues raised by UAT's constantly; specifically (#374 , #345, #316)

Created a tooltip below the publish checkbox, explaining what it means
![image](https://user-images.githubusercontent.com/44992275/65428594-ff676d00-de57-11e9-9078-b3305ba725dc.png)

Updated the wording in the alert notifications
![image](https://user-images.githubusercontent.com/44992275/65428700-29b92a80-de58-11e9-99ef-97e73793d273.png)

I also think we should look into better-looking alert boxes as default ones tend to be ignored as they look like generic popups.

Happy to take suggestions for better wording etc.

Should probably commit this before the UAT on Tuesday...

2019-09-23 14:12 UTC, aidengeorge97 requested changes
I just have minor nitpicky suggestions. I think this solution is perfectly reasonable as is but could be polished more.

I think it would be neater to have the publish tooltip only appear on a hover or help button? Or rather than wording it as an instruction have it as a warning that is consistent with the notification "Unpublished programs will not appear to students or be selectable as a requirement elsewhere."

For the popup notification, perhaps this could be formatted to be consistent with our other pop-up dialogs?

2019-09-24 01:55 UTC, j-selby commented
For reference, I displayed a confirmation box in one of the earlier related issues because it blocks execution and allows us to fairly simply check stuff before form submission. With that said, this approach could be improved.

2019-09-24 13:53 UTC, KavsHub commented
Yep, I'll look into hidden tooltips (may as well make them for other sections while I'm at it)

I also wanted to explore changing the checkbox to maybe a slider or something with draft-publish so that they know that drafts are not searchable

2019-09-25 01:51 UTC, joshcbee commented
Will create a new issue, but from today's user testing:
      What do I do with the publish button – correctly surmises that the button would make it live for students – any reason why we have the publish button where it is – seems out of order when first creating a plan – not important in the beginning while still entering the information.
-        Save prompt comes up for publishing again – if I’m saving as I go, I don’t need the publish text, when I save and exit would want to see the publish sign, staying on the page it’s not relevant.

2019-09-26 10:33 UTC, merged