Refactor rules
j-selby/CASS-Degrees-Code pull request #394
Opened 2019-09-24 07:25 UTC by j-selby

This was painful...

Closes #367

This PR breaks apart rules into individual files, cleaning them up along the way. In doing this, I have attempted to remove duplicated logic, minimise the amount of information loaded for pages (i.e courses doesn't need program-specific rules), reduce LOCs across the board, and get rid of rulescripts entirely.

Further, I have tried to enforce ES6 throughout these new files.

This may break old course lists (due to change in name of vue object) - this was done to reduce ambiguity, but this needs to be verified independently.

2019-09-26 01:53 UTC, Daniel-Jang commented
I was testing out the features and unfortunately, javascript spits out errors:
![image](https://user-images.githubusercontent.com/37033052/65652026-aebc6380-e053-11e9-880c-90a9cbb9cc09.png)

When you add a course rule in either or rule, the course rule is empty and the error appears (shown on the right side of the screenshot)

2019-09-26 01:58 UTC, Daniel-Jang commented
Also, just a heads up, when you pull from develop (I have pulled both from develop and your branch to work on my "rule reordering" issue), you will see the following error when you try and resolve merge conflicts as well:

![image](https://user-images.githubusercontent.com/37033052/65652392-f5f72400-e054-11e9-81a4-e6c0292c5976.png)

2019-09-26 03:21 UTC, j-selby commented
@Daniel-Jang the first one was something I missed - that should be easily fixable. The second one was because they didn't merge properly - I will rebase this after everyone gets their PRs through (else we will be here all night)

2019-09-26 04:25 UTC, Daniel-Jang commented
> @Daniel-Jang the first one was something I missed - that should be easily fixable. The second one was because they didn't merge properly - I will rebase this after everyone gets their PRs through (else we will be here all night)

Ah okay, I'll keep following this branch as my branch currently depends on yours (you will have to merge yours in first).

2019-09-27 07:09 UTC, j-selby commented
Rebased onto the latest develop branch.

2019-09-28 07:40 UTC, JackSekoranja requested changes
After initial testing I found that I couldn't submit anything because the rules function is invalid (See suggestions). Note that if the following suggestions are added, there will be inconsistencies with the naming of export rules (i.e. `export_requirements` and `exportRules`), therefore we will need to decide whether we want to use camel case or snake case for our javascript functions.

2019-09-28 07:40 UTC, JackSekoranja commented on cassdegrees/templates/staff/creation/createcourse.html
> +            if (app.export_rules()) {
```suggestion
            if (app.exportRules()) {
```

2019-09-28 07:40 UTC, JackSekoranja commented on cassdegrees/templates/staff/creation/createprogram.html
> +            if (globalRequirementsApp.export_requirements() && app.export_rules()) {
```suggestion
            if (globalRequirementsApp.export_requirements() && app.exportRules()) {
```

2019-09-28 07:40 UTC, JackSekoranja commented on cassdegrees/templates/staff/creation/createsubplan.html
> +            app.export_rules();
```suggestion
            app.exportRules();
```

2019-09-28 07:40 UTC, JackSekoranja commented on cassdegrees/templates/staff/creation/createsubplan.html
> +            if (globalRequirementsApp.export_requirements() && app.export_rules()) {
```suggestion
            if (globalRequirementsApp.export_requirements() && app.exportRules()) {
```

2019-09-28 07:40 UTC, JackSekoranja commented on cassdegrees/templates/staff/creation/createprogram.html
> +            app.export_rules();
```suggestion
            app.exportRules();
```

2019-09-28 07:59 UTC, j-selby commented
Didn't spot that one, sorry. Yeah - we will either need to change exportRules or all the other functions - this was mostly inconsistent before, though I was targeting underscores mostly.

2019-09-28 10:19 UTC, j-selby commented
@JackSekoranja I've gone ahead and changed `exportRules` to be `export_rules` (for consistency with most of the other Vue rules) - might need to go through soon and fix the rest up (and maybe consider a Javascript linter?)

2019-09-28 14:25 UTC, JackSekoranja approved these changes
Can't find any issues. Happy for you to merge.

2019-09-29 09:55 UTC, merged