Course List Styling Review
j-selby/CASS-Degrees-Code pull request #413
Opened 2019-09-26 04:11 UTC by aidengeorge97

Closes #368.

This PR serves to address interface issue users have identified in testing. The key issues were
* The "Add Courses from Existing List" button confused the tester, who attempted to click it to add new courses
* The tester found it difficult to determine when a course was accepted (Perhaps some kind of animation would help here)

To address the second point, I have made it so that the most recently added course now appears at the top of the list. This makes it clear that a course has been added, at the cost of not keeping the list in a sorted ordering. To mitigate this cost I have added an additional tool button which allows the users to sort the list by course code. These changes will allow users to immediately see when a course is added, while still being able to easily search through existing lists.

To address the first point I have changed the wording of the button and reformatted it to match the other added buttons. I believe the size/placement of the original button and its wording was overselling its importance to the addition of courses. This may still require further testing, but I feel user confusion comes more from unfamiliarity with the List functionality within the system as a whole.

Lastly I have added the ability to expand/collapse course lists to keep the whole user interface clean. 

![image](https://user-images.githubusercontent.com/37424867/65657479-fa2c3d00-e066-11e9-92ee-e6cc83580ec5.png)

![image](https://user-images.githubusercontent.com/37424867/65657601-6c048680-e067-11e9-9736-a87fcf2310e9.png)

![image](https://user-images.githubusercontent.com/37424867/65657611-7c1c6600-e067-11e9-9232-0c6fbe0c3118.png)

2019-09-26 05:49 UTC, j-selby requested changes
A few minor tweaks, looks good otherwise!

2019-09-26 05:49 UTC, j-selby commented on cassdegrees/templates/widgets/staff/courselistingwidget.html
> +    <div style="text-align:right; width:100%; padding:0; padding-bottom: 5px">
Does this need to be hardcoded here? Would be nice if this could be extracted to CSS

2019-09-26 05:49 UTC, j-selby commented on cassdegrees/templates/widgets/staff/rulescripts.html
> +        <ul class="resources-list" v-if="!is_hidden_courses">
`is_hidden_courses` doesn't seem like the best naming scheme here - `is_courses_view_hidden` maybe?

2019-09-26 05:49 UTC, j-selby commented on cassdegrees/templates/widgets/staff/subplanrules.html
> +            <div style="text-align:right; width:100%; padding:0; padding-bottom: 5px">
See above re: CSS.

2019-09-26 06:35 UTC, aidengeorge97 commented
Thanks for the feedback, I've made those tweaks!

2019-09-30 00:24 UTC, j-selby commented
Rebase this one (sorry!) and I'd be happy to approve.

2019-10-02 13:31 UTC, aidengeorge97 commented
This branch had too many conflicts to reasonably merge so I started from scratch on a separate branch. See #439 for the new PR.

2019-10-02 13:31 UTC, closed without merging