Student portal page for end of project
j-selby/CASS-Degrees-Code pull request #458
Opened 2019-10-07 06:23 UTC by KavsHub

Issue: #341 (Basic student portal for end of Semester 2)

*Initial commit (Work in progress)*

Currently accessible by: {HOST_IP}/portal

Pretty much follows the same style we currently have for the student planner except when you click on the program it takes you to the pdf template for the plan in a new tab.

![image](https://user-images.githubusercontent.com/44992275/66288862-a0f5c080-e926-11e9-8a69-0410d037023c.png)

![image](https://user-images.githubusercontent.com/44992275/66288878-ace18280-e926-11e9-9408-030c9957bb72.png)

I'm trying to add pagination to it now so that it doesn't load 100 programs on one page.

Open to feedback and naming changes. (Wasn't sure what we wanted to call the page so it's called 'portal' for now)

I also call the staff pdf function, should make a student version for it? or it is safe doing what I'm currently doing? (I've tested and it works when you're not logged in)

2019-10-07 06:26 UTC, KavsHub commented
I might also group programs by year like the way its currently done on CASS's website

2019-10-07 07:04 UTC, j-selby requested changes
Looks good, but a few comments:

- Link from/to homepage would be good ("Looking for printable PDFs? Click here" kinda deal)
- Make sure to update the breadcrumbs at the top of the page
- This exposes the fact that non-public plans can have PDFs generated - potential security risk

2019-10-07 07:04 UTC, j-selby commented on cassdegrees/static/js/student/list.js
> +var programSearch = new List('programs', options);
Newline

2019-10-07 07:04 UTC, j-selby commented on cassdegrees/templates/student/portal.html
> +{% endblock %}
Newline.

2019-10-08 11:43 UTC, pep8speaks commented
Hello @KavsHub! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cassdegrees/ui/views/student.py`](https://github.com/cass-degrees/CASS-Degrees-Code/blob/7db9b7ab07fe583aeb841cdd9846ba82da75f1d1/cassdegrees/ui/views/student.py):

> [Line 305:73](https://github.com/cass-degrees/CASS-Degrees-Code/blob/7db9b7ab07fe583aeb841cdd9846ba82da75f1d1/cassdegrees/ui/views/student.py#L305): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2019-10-08 11:47 UTC, KavsHub commented
Pagination has been added. + other small things that were mentioned and discovered.

2019-10-08 14:53 UTC, Daniel-Jang approved these changes
Seems nice and simple to me, happy to approve.

2019-10-08 23:03 UTC, JackSekoranja requested changes
Hate to be the one to point this out, but part of this PR was to hide the student plan creation (since it was only a prototype). What should happen is the base URL goes to the student portal and the prototype should go under ‘/prototype’ or something similar. The prototype should also not be accessible to students, so make sure to use authentication on it

2019-10-09 11:40 UTC, KavsHub commented
Okay cool I'll switch the pages and URLs around.

2019-10-09 12:01 UTC, KavsHub commented
Okay, the student portal is now the new index.html and I've added authentication to all the student planner (prototype) pages. - Access by going to /prototype

2019-10-09 12:24 UTC, KavsHub commented
Issue of security of unpublished plan pdf viewing raised by @j-selby has been solved.
I've now added a login check if trying to view an unpublished plan.

2019-10-10 06:30 UTC, JackSekoranja approved these changes
Very nice solution, happy for you to merge

2019-10-10 13:32 UTC, merged