Implement basic degree creation workflow
j-selby/CASS-Degrees-Code pull request #59
Opened 2019-04-14 05:40 UTC by j-selby

This PR adds a page for a CASS Staff member to be able to create degrees. Verification is included to ensure that pre-existing degrees are not overwritten, with an appropriate error message displayed if this is the case.

Resolves #6, resolves #17

![EightXenon](https://user-images.githubusercontent.com/1404334/56088824-acae8000-5ecb-11e9-8210-76827c836f31.png)

2019-04-14 11:23 UTC, JackSekoranja requested changes
I'm having a minor issue on the main menu where the 'Create Program Template' isn't centred, so it would be good if that could be fixed. Also, the first acceptance criteria for #6 was _"It is possible to navigate from the system’s homepage to the template creation tool"_. However, the current changes don't do this, as after adding a template it just gets put in to the database and the user is notified. To fix, just link to a blank page that will host the creation tool. I also checked creating a duplicate course and it worked perfectly. No other issues

2019-04-15 04:57 UTC, j-selby commented
`It is possible to navigate from the system’s homepage to the template creation tool`
I understood this to simply be navigating from the root page (/) to the creation page itself. Is this not the idea agreed on within e.g. https://github.com/cass-degrees/CASS-Degrees-Code/pull/55, or does this mean something different.

2019-04-15 05:16 UTC, JackSekoranja commented
I think your assumption is correct, although the 'template creation tool' was the page that allows you to add information about the degree requirements (Global restrictions, Majors, Courses, etc.). My issue was that after successfully adding a course the page does not change (i.e. you can still add new courses as opposed to being in the edit tool). What should happen is the ability to add courses is removed and you begin 'editing' the course you just added

2019-04-16 03:34 UTC, j-selby commented
@JackSekoranja I had in mind that it would be a singular page tool, rather then having different, inconsistent UIs for this stuff. Is this a bad idea?

2019-04-16 03:46 UTC, JackSekoranja commented
@j-selby Not a bad Idea, consistency is always something we should strive for, although it may make less sense depending on what you mean. If you are talking about a 'singular page tool' as something that is the same between Templates and Subplans, then the implementation may be a bit messy since there are slightly different rules for both. However, If you are talking about the 'singular page tool' as a shared page between the creation itself and the actual building of the rules then I think that's a good idea, but I think the creation tab should at least hide or become an edit tool for the story to be considered complete.

2019-04-16 04:45 UTC, joshcbee requested changes
Can successfully add a new plan. Successfully rejected when code and year duplicated.

Currently fails criteria 2 for #17 - year and title
![image](https://user-images.githubusercontent.com/10462891/56182437-8f0d2200-6055-11e9-99d4-8f581d83f6e3.png)

- Terminology should be consistent - e.g URL for user is currently 'create_degree' rather than 'create program'
- Suggest legend of form field changed from 'Add program template' to 'Program Details' to avoid duplication and build consistency across forms.
- Suggest changing error message to reflect nature of issue (e.g. program with the same code and year already exists.

2019-04-16 05:54 UTC, j-selby commented
`Currently fails criteria 2 for #17 - year and title`
Hmmm... Is this possible to enforce on the data model side of things?

`Terminology should be consistent - e.g URL for user is currently 'create_degree' rather than 'create program'`
OK, can do.

`However, If you are talking about the 'singular page tool' as a shared page between the creation itself and the actual building of the rules then I think that's a good idea, but I think the creation tab should at least hide or become an edit tool for the story to be considered complete.`
This was my understanding. I think making some fields in the creation tab read only (title + unit count can be changed freely I  guess) is much simpler then having different UIs for this.

2019-04-16 06:01 UTC, j-selby commented
Fixed homepage buttons for the changes in this PR, changed URL, rebased with `develop`.

2019-04-16 10:54 UTC, JackSekoranja commented
So the Year and Title issue can be fixed relatively easily. In my PR (#62) I added all the necessary imports that you'll need to check existence of the Year-Title relationship. To avoid merge issues I'd want it pushed first, but once it's done you could write something like `list(DegreeModel.objects.filter(name__iexact=new_name, year=int(year)).values())` and if that was empty then there wouldn't be any pre-existing relationship.

2019-04-17 06:10 UTC, j-selby commented
Year and name of program now verified for uniqueness. Error messages clarified (i.e to specify conflicts with name, code and year, if they occur). Rebased with `develop`.

2019-04-17 12:19 UTC, JackSekoranja requested changes
Since you wanted to stay on the same page when adding the actual course components, I've suggested code changes that will re-fill the form correctly rather than deleting all the contents. Since the user story this completes has an acceptance criteria saying the user needs to be directed to the program creation page, we need to make sure the page reflects a proper creation tool after submitting, hence the need to keep the input values for the template. After implementing these changes I would be happy to approve the PR.

2019-04-17 12:19 UTC, JackSekoranja commented on cassdegrees/ui/views.py
> +
```suggestion

        for k, v in degree_dict.items():
            render_properties[k] = v
            
```

Same changes as Josh, allows inputted values to appear in the form once it has been re-submitted

2019-04-17 12:19 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
> +                <input class="text" id="code" type="text" name="code" aria-required="true" placeholder="e.g. BARTS" required>
```suggestion
                <input class="text" id="code" type="text" name="code" aria-required="true" placeholder="e.g. BARTS" required value="{{ code|default:"" }}">
```

Makes the code value autofill once the page is sent

2019-04-17 12:19 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
> +                <input class="text" id="name" type="text" name="name" aria-required="true" placeholder="e.g. Bachelor of Arts" required>
```suggestion
                <input class="text" id="name" type="text" name="name" aria-required="true" placeholder="e.g. Bachelor of Arts" required value="{{ name|default:"" }}">
```

Makes the name value autofill once the page is sent

2019-04-17 12:19 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
> +                <input class="text" id="year" type="number" min="2000" max="2100" value="2019" name="year" aria-required="true" required>
```suggestion
                <input class="text" id="year" type="number" min="2000" max="2100" value="{{ year|default:"2019" }}" name="year" aria-required="true" required>
```

Makes the year value autofill once the page is sent

2019-04-17 12:19 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
> +                <input class="text" id="units" type="number" min="0" max="1000" value="144" name="units" aria-required="true" required>
```suggestion
                <input class="text" id="units" type="number" min="0" max="1000" value="{{ units|default:"144" }}" name="units" aria-required="true" required>
```

Makes the units value autofill once the page is sent

2019-04-17 12:19 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
> +                <select id="degreeType" name="degreeType" aria-required="true" required>
```suggestion
                <select id="degreeType" name="degreeType" aria-required="true" required value="{{ degreeType|default:"" }}>
```

Makes the degree type autofill once the page is sent

2019-04-17 12:34 UTC, pep8speaks commented
Hello @j-selby! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cassdegrees/ui/views.py`](https://github.com/cass-degrees/CASS-Degrees-Code/blob/d97804cc8e7be77d150565db732aa3104aa79b64/cassdegrees/ui/views.py):

> [Line 186:1](https://github.com/cass-degrees/CASS-Degrees-Code/blob/d97804cc8e7be77d150565db732aa3104aa79b64/cassdegrees/ui/views.py#L186): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-04-17 12:35 UTC, j-selby commented
Actual editing is out of scope for this PR (kinda getting a bit big now), but I'll apply those anyway. Thanks!

2019-04-17 12:37 UTC, JackSekoranja approved these changes
Looks good, happy to merge.

2019-04-17 21:04 UTC, joshcbee approved these changes
Happy to merge.

2019-04-18 02:46 UTC, merged