Add support for adding/removing global requirements from a program
j-selby/CASS-Degrees-Code pull request #67
Opened 2019-04-18 03:10 UTC by j-selby

This is quite a big PR, so buckle in!

This PR adds support for specifying global requirements when creating a program. The intent is to re-use this entire page for editing a program.

Resolves #15. Resolves #16.

![RobustWombat](https://user-images.githubusercontent.com/1404334/56334343-4b442500-61db-11e9-9d80-8e0ab98f79bd.png)

FAQ:

- Why the custom serialization stuff?

While web browsers *technically* support lists in forms, they are not designed to group elements together (in, say, a global requirement or rule). Effectively, the work for this is now done on the client, rather than what would already have to be done on the server.

- Why a JSON field?

As per rules, this field allows for greater flexibility in storing the data, where a minor performance hit is a non-issue.

- Why the templating system?

Different kinds of global requirements/rules do need to be modeled throughout the life of the program, and this needed some degree of flexibility. We could have relied on the server constantly regenerating the server-side template for this, but that is poor UX for reasons of constantly having the page reload.

This solution, while requiring a bit more code, solves the UX dilemma.

- Why did I use Pristine?

Web browser's validation of forms was inconsistent for this, and didn't verify stuff like select boxes. Pristine was a 3 line addon to fix this and added proper messages. Alternatives required greater amounts of manipulation, or jQuery, which was way too overkill.

2019-04-18 05:00 UTC, JackSekoranja requested changes
The only change I'd request you make is to hide the "Add Global Requirements" pane until the user actually creates a course. I'm open to discussion about this if you think it should be different, I just feel that it forces users to actually 'create' the plan first, which will remove the likelihood of people accidentally starting duplicate plans. 

I also think the remove requirement is a little awkward and it might be better to replace it with some kind of cross and/or reposition it, but for now I'm happy for you to leave it.

2019-04-18 05:16 UTC, j-selby commented
```
The only change I'd request you make is to hide the "Add Global Requirements" pane until the user actually creates a course. I'm open to discussion about this if you think it should be different, I just feel that it forces users to actually 'create' the plan first, which will remove the likelihood of people accidentally starting duplicate plans.
```
Yep! Can do. I'll leave this as-is until the edit page is linked in (so we don't accidentally break it in the meantime).

```
I also think the remove requirement is a little awkward and it might be better to replace it with some kind of cross and/or reposition it, but for now I'm happy for you to leave it.
```
Do agree. Not a bad idea - I'll have a brainstorm on it.

2019-04-18 07:39 UTC, JackSekoranja requested changes
I mentioned this before, but unless you make the following changes the degreeType field won't carry across

2019-04-18 07:39 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
> +                <select id="degreeType" name="degreeType" aria-required="true" required value="{{ degreeType|default:"" }}">
```suggestion
                <select id="degreeType" name="degreeType" aria-required="true" required>
```
Realised `value` here doesn't do anything

2019-04-18 07:39 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
>                      <option value="ugrad-sing" selected>Undergraduate Single Pass Degree</option>
```suggestion
                     <option value="ugrad-sing" {% if degreeType == "ugrad-sing" %}selected{% endif %}>Undergraduate Single Pass Degree</option>
```

Mark as selected if degreeType is ugrad-sing

2019-04-18 07:39 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
>                      <option value="ugrad-doub">Undergraduate Flexible Double Degree</option>
```suggestion
                     <option value="ugrad-doub" {% if degreeType == "ugrad-doub" %}selected{% endif %}>Undergraduate Flexible Double Degree</option>
```

Mark as selected if degreeType is ugrad-doub

2019-04-18 07:39 UTC, JackSekoranja commented on cassdegrees/templates/createprogram.html
>                      <option value="hon">Honours Degree</option>
```suggestion
                     <option value="hon" {% if degreeType == "hon" %}selected{% endif %}>Honours Degree</option>
```

Mark as selected if degreeType is hon

2019-04-18 12:12 UTC, JackSekoranja approved these changes
Looks good :)

2019-04-22 02:08 UTC, j-selby commented
Been a couple of days, so I will merge this one now (as previously agreed policy).

2019-04-22 02:08 UTC, merged